{
  "formatVersion": "1.1",
  "component": {
    "group": "it.unito.di",
    "module": "moise-accountability",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "moise-accountability-0.1.jar",
          "url": "moise-accountability-0.1.jar",
          "size": 371683,
          "sha512": "0c90e5869bdb237bf3a47f912210c8ff02f742ba07cfc403427ee4ec2709136d5e6a0d8633007d9214807467f3ec6584b7caccf04f7801cdd22ae65f019bb3b9",
          "sha256": "5fea581ab4cbbee6cda154a175288540a4112b6a65f51e52672fd57ced0f776d",
          "sha1": "4693e7fbf301f572d072d707e428fd390ab51921",
          "md5": "095d3276c88dacd9d0c638f5eea8d0ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason-lang",
          "module": "jason",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.jacamo",
          "module": "npl",
          "version": {
            "requires": "0.5-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jacamo",
          "module": "cartago",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.jacamo",
          "module": "jaca",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.+"
          }
        },
        {
          "group": "guru.nidi",
          "module": "graphviz-java",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "moise-accountability-0.1.jar",
          "url": "moise-accountability-0.1.jar",
          "size": 371683,
          "sha512": "0c90e5869bdb237bf3a47f912210c8ff02f742ba07cfc403427ee4ec2709136d5e6a0d8633007d9214807467f3ec6584b7caccf04f7801cdd22ae65f019bb3b9",
          "sha256": "5fea581ab4cbbee6cda154a175288540a4112b6a65f51e52672fd57ced0f776d",
          "sha1": "4693e7fbf301f572d072d707e428fd390ab51921",
          "md5": "095d3276c88dacd9d0c638f5eea8d0ae"
        }
      ]
    }
  ]
}
